---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wavving-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wavving
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
